# Generated by Django 3.1.4 on 2025-08-07 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0032_auto_20250803_0713'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('course', models.CharField(max_length=100)),
                ('completion_date', models.DateField()),
                ('certificate', models.FileField(blank=True, null=True, upload_to='certificates/')),
            ],
        ),
    ]
