# Generated by Django 3.1.4 on 2025-08-07 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0033_student'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
