from django.db.models.signals import post_save
from django.dispatch import receiver
from .models import Student
from reportlab.pdfgen import canvas
from reportlab.lib.pagesizes import A4
from reportlab.lib.utils import ImageReader
from reportlab.lib.colors import HexColor
import os

@receiver(post_save, sender=Student)
def generate_certificate(sender, instance, created, **kwargs):
    if created and not instance.certificate:
        os.makedirs('media/certificates', exist_ok=True)
        file_path = f"media/certificates/{instance.name.replace(' ', '_')}_certificate.pdf"

        # Create canvas
        c = canvas.Canvas(file_path, pagesize=A4)
        width, height = A4

        # Draw background
        try:
            bg = ImageReader('mainapp/static/images/certificate_bg.jpg')
            c.drawImage(bg, 0, 0, width=width, height=height)
        except:
            pass  # continue without background

        # Text styling
        c.setFont("Helvetica-Bold", 24)
        c.setFillColor(HexColor("#4A148C"))
        c.drawCentredString(width/2, height - 150, "Certificate of Completion")

        c.setFont("Helvetica", 16)
        c.setFillColor(HexColor("#000000"))
        c.drawCentredString(width/2, height - 200, "This is to certify that")

        c.setFont("Helvetica-Bold", 20)
        c.drawCentredString(width/2, height - 240, instance.name)

        c.setFont("Helvetica", 16)
        c.drawCentredString(width/2, height - 280, "has successfully completed the course")

        c.setFont("Helvetica-Bold", 18)
        c.drawCentredString(width/2, height - 310, instance.course)

        c.setFont("Helvetica", 14)
        c.drawCentredString(width/2, height - 360, f"Date: {instance.completion_date.strftime('%d %B %Y')}")

        c.setFont("Helvetica-Oblique", 12)
        c.drawCentredString(width/2, 100, "Generated by E-Learning Portal")

        c.showPage()
        c.save()

        instance.certificate.name = file_path.replace("media/", "")
        instance.save()
        print("🔥 Certificate Signal Triggered for:", instance.name)